# remove NOTE about no visible binding for global variable during R CMD check --
if (getRversion() >= "2.15.1") {
  utils::globalVariables(
    c("ID", "CloneID", "SnpPosition", "CallRate", "AvgCountRef", "AvgCountSnp",
      "RepAvg", "NOT_USEFUL", "SNP", "CALL_RATE", "AVG_COUNT_REF",
      "AVG_COUNT_SNP", "REP_AVG", "NEW_ID", "SNP_N", "ALLELE_NAME", "ALLELE_NUMBER",
      "ALLELES_COUNT", "GENOTYPED_PROP", "MISSING_IND_PROP", "AlleleID", "HET_NUMBER",
      "HET_PERCENT", "HET_PROP", "everything", "DP", "AD", "vcf.headers",
      "GT_VCF", "INDIVIDUALS2", "ALLELE_REF_DEPTH",
      "ALLELE_ALT_DEPTH", "GT_BIN", "GT_HAPLO", "REF_NEW", "REF_ALT_CHANGE",
      "GT_VCF_A1", "GT_VCF_A2", "MAF", "Allele1", "Allele2", "POP", "IN_GROUP",
      "OUT_GROUP", "ID.FILTER", "ANCESTRAL", "SEQUENCES", "GARBAGE", "SNP_READ_POS",
      "FASTA_REF", "BP", "Chr", "Locus", "Locus ID", "Col", "PP", "ALLELE_GROUP",
      "PROBLEM", "IND_LEVEL_POLYMORPHISM", "HOM", "HET", "N_GENOT", "DIPLO",
      "FREQ_ALLELES", "HOM_E", "HOM_O", "FH", "HET_O", "HET_E", "PI", "pi",
      "MONOMORPHIC", "POLYMORPHIC", "CONSENSUS", "PARALOGS", "Seg Dist",
      "REF.x", "ALT.x", "REF.y", "ALT.y", "BLACKLIST", "ALLELE_COVERAGE_RATIO",
      "..scaled..", "GENOTYPE_LIKELIHOOD_GROUP", "GL_MAX", "GL_MIN", "VALUE",
      "GL_DIFF", "ALLELE_ALT_DEPTH_NEW", "ALLELE_REF_DEPTH_NEW", "ALT_NEW",
      "CHANGE", "n.al.pop", "n.al.tot", "TOTAL_READ", "Missingness",
      "MISSING_GENOTYPE", "INDIVIDUALS_NUMBER", "PERC", "Axis.1", "Axis.2", "V1",
      "Axis.3", "Axis.4", "ids", "GQ", "PL", "ARTIFACTS", "GENOTYPED",
      "IND_THRESHOLD", "N_IND", "PERCENT", "POP_GENOTYPED", "PROB_POP", "LOCUS",
      "HET_DIFF", "HET_O", "HET_MAX", "GT", "GL", "INDIVIDUALS", "POP_ID", "N",
      "HET_O", "HOM_O", "HET_E", "HOM_E", "FREQ_ALT", "FREQ_REF",
      "GLOBAL_MAF", "PP", "PQ", "QQ", "AND", "OR", "filters.parameters",
      "het.global.summary", "het.global.threshold",
      "plot.distribution.het.local", "violinplot.het.global",
      "violinplot.het.local", "HET_GROUP", "HET_MIN",
      "HET_THRESHOLD", "POP_THRESHOLD", "PROP", "0.4", "0.9","DIF_0.1", "DIF_0.9",
      "DIF_OUTLIERS", "DIF_THRESHOLD", "HET_DIF", "HET_MEAN", "MAX_0.4",
      "MAX_0.9", "MAX_DIF_OUTLIERS", "MAX_DIF_THRESHOLD", "MAX_OUTLIERS",
      "MAX_THRESHOLD", "OUTLIERS", "THRESHOLD", "WHITELIST", "het.dif.threshold",
      "ALT2", "REF2", "#CHROM", "A1", "A2", "ALLELES", "ALLELES_GROUP", "ALT",
      "COL1", "COL3", "COL4", "COUNT", "ERASE", "FILTER", "FORMAT", "FORMAT_ID",
      "INDIVIDUALS_ALLELES", "INFO", "KEEPER", "MAF_GLOBAL", "MAF_LOCAL",
      "MARKERS", "MARKERS_ALLELES", "MARKER_NUMBER", "MAX_COUNT_MARKERS",
      "NUMBER", "QUAL", "READ_DEPTH", "REF", "STRATA", "TOTAL",
      "path.folder.step1", "path.folder.step2", "sum.pop", "EIGENVALUES",
      "MISSING_GENOTYPE_PROP", "A1_A2", "ALLELE_COPIES", "READ_DEPTH_MEAN",
      "READ_DEPTH_MIN", "READ_DEPTH_MAX", "ALLELE_REF_DEPTH", "ALLELE_REF_DEPTH_MEAN",
      "ALLELE_REF_DEPTH_MIN", "ALLELE_REF_DEPTH_MAX", "ALLELE_ALT_DEPTH",
      "ALLELE_ALT_DEPTH_MEAN", "ALLELE_ALT_DEPTH_MIN", "ALLELE_ALT_DEPTH_MAX",
      "GL", "GL_MEAN", "ALLELE_SUM", "FIS", "FIS_MAX", "FIS_MIN", "FIS_DIFF",
      "FREQ", "HOM_ALT",
      "fh", "HOM_REF", "BETAI", "HB", "HW", "NN", "NN_C", "N_POP", "N_POP_C",
      "DIFFERENT", "DISTANCE", "ID1", "ID2", "IDENTICAL", "IDENTICAL_GT",
      "PAIRWISE", "POP_COMP", "PROP_IDENTICAL", "TOTAL_MARKERS_GENOTYPED", "X1",
      "HET_RANGE", "MISSING_GROUP", "MISSING_PROP", "MISSING_PROP_OVERALL",
      "MISSING_PROP_POP", ".", "ALLELE", "ALLELE1", "ALLELE2", "ALLELES_FREQ",
      "Catalog ID", "Cnt", "GENOTYPE", "GROUP", "HAPLOTYPES", "MARKERS.ALLELE_GROUP",
      "POLYMORPHISM", "ALT_ALLELE_NUMBER", "PROB_HET", "PROB_HOM_ALT", "PROB_HOM_REF",
      "NAPL", "DISTANCE_RELATIVE", "MARKERS_COMMON", "id.pairwise", "input.prep",
      "CHROM_LOCUS", "NEW_MARKERS", "POP_ID_N", "INDIVIDUALS_N", "GT_N", "GT_IMP",
      "INDIVIDUALS_REP", "KEEP", "GT_VCF_NUC", "INTEGERS", "GOF", "NR", "NV",
      "A1_NUC", "A2_NUC", "RANK", "MAF_P", "MAF_L", "BAD_ID", "strata",
      "SPLIT_VEC", "ALLELES_COUNT_OVERALL", "N_INV", "HS", "GIS", "PI_NEI",
      "FQ_FILES", "PARAMETER", "SPLIT", "mtime", "REF_ALT", "ARTIFACT",
      "HETEROZYGOSITY", "HOMOZYGOSITY", "LOCUS_NUMBER", "BLACKLIST_ARTIFACT",
      "HAPLOTYPE", "MAX_NUMBER_SNP_LOCUS", "MEAN_NUMBER_SNP_LOCUS",
      "NUMBER_LOCUS_4SNP", "SNP_LOCUS", "SNP_NUMBER", "BLACKLISTED_FLAG",
      "BLACKLIST_USTACKS", "FILTERED", "FOR_CATALOG",
      "HAPLOTYPE_NUMBER", "LOCUS_TOTAL", "LUMBERJACKSTACK_FLAG", "SEQUENCE",
      "SEQ_TYPE", "ALLELE_N", "BAYESCAN_MARKERS", "BAYESCAN_POP", "COVERAGE",
      "GENE_N", "SNP_NUM", "ALPHA", "FST", "FST_GROUP", "ITERATIONS", "LOG10_PO",
      "LOG10_Q", "POST_PROB", "PO_GROUP", "Q_VALUE", "SELECTION", "ACCURACY",
      "SELECTION_TYPE_ON_LOCUS", "Distance", "R", "A", "NEW_GT", "Markers", "READS",
      "CONSENSUS_MAX", "REF_OLD", "ORIG_GT", "GT_1", "GT_2", "TEMP", "VCF_A1",
      "VCF_A2", "IMBALANCE_PERCENT", "LOW_COVERAGE_PERCENT", "BLACKLIST_PSTACKS", "n",
      "COL", "COL_TYPE", "DELETE", "OR_POP_THRESHOLD", "POLYMORPHIC.x",
      "POLYMORPHIC.y", "EXPECTED", "FREQ_HET_E", "FREQ_HET_O", "FREQ_HOM_ALT_E",
      "FREQ_HOM_ALT_O", "FREQ_HOM_REF_E", "FREQ_HOM_REF_O", "GENOTYPES",
      "N_HET_EXP", "N_HOM_ALT_EXP", "N_HOM_REF_EXP", "OBSERVED",
      "DISCARD", "NUMBERS", "TARGET_ID", "iter", "m", "PRIVATE_ALLELES",
      "GENOTYPED_MAX", "PAIRS", "NN_G", "N_GLOBAL", "N_LOCAL", "PP_G", "QQ_G",
      "DIFF", "HAPLOTYPES_NEW", "NUC", "ALT_GLOBAL", "ALT_LOCAL", "GLOBAL",
      "LOCAL", "OVERALL", "HQ"
    )
  )
}
